apiVersion: v1
kind: Service
metadata:
  labels:
    app: pushgateway
  name: pushgateway
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 9091
      nodePort: 30091
      protocol: TCP
      targetPort: 9091
  selector:
    app: pushgateway
  sessionAffinity: None