apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    name: prom-pvc
    namespace: monitoring
  hostPath:
    path: "/var/log/prom/"

